# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
            pip install -e .
            cp .circleci/conftest.py tests/conftest.py
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/

  style:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: run pycodestyle
          command: |
            . venv/bin/activate
            pycodestyle ~/repo/motorturbine

  test:
    docker:
      - image: circleci/python:3.6.1
      - image: mongo:3.4
        command: [mongod, --smallfiles]
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: run pytest
          command: |
            . venv/bin/activate
            pytest

  push_pypi:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: dist
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install wheel twine
            python3 setup.py sdist bdist_wheel
            twine upload -u $PYPI_USER -p $PYPI_PASS dist/*

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - style:
          requires:
            - build
      - test:
          requires:
            - build
      - push_pypi:
          requires:
            - style
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/